name: Trigger Deploy
on:
  push:
    branches: [main]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy in infra
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ilichfer/infra-tienda-ropa/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"main"}'
